import {
  Plus,
  Trash,
  Pencil,
  Search,
  Check,
  X,
  Menu,
  LayoutDashboard,
  CarFront,
  Wrench,
  Fuel,
  ChartBar,
  SidebarClose,
  SidebarOpen,
  EyeIcon,
  EyeOff,
} from 'lucide-react'

export const icons = {
  plus: Plus,
  trash: Trash,
  edit: Pencil,
  search: Search,
  check: Check,
  close: X,
  menu: Menu,
  dashboard: LayoutDashboard,
  car: CarFront,
  wrench: Wrench,
  fuel: Fuel,
  chart: ChartBar,
  sidebarClose: SidebarClose,
  sidebarOpen: SidebarOpen,
  eyeOn: EyeIcon,
  eyeOff: EyeOff,
} as const
