export const errorCodeMap = {
  /* user */
  USER_EXISTS: 'USER_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  PASSWORD_UPDATE_FAILED: 'PASSWORD_UPDATE_FAILED',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
  PASSWORD_SAME_AS_CURRENT: 'PASSWORD_SAME_AS_CURRENT',
  PASSWORD_RESET_TOKEN_INVALID: 'PASSWORD_RESET_TOKEN_INVALID',

  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  EMAIL_VERIFICATION_RESEND_TOO_SOON: 'EMAIL_VERIFICATION_RESEND_TOO_SOON',
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',

  PHONE_ALREADY_IN_USE: 'PHONE_ALREADY_IN_USE',

  /* auth */
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_INVALID: 'SESSION_INVALID',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',

  REFRESH_TOKEN_REUSE_DETECTED: 'REFRESH_TOKEN_REUSE_DETECTED',

  /* car care */
  CAR_CARE_PRODUCT_NOT_FOUND: 'CAR_CARE_PRODUCT_NOT_FOUND',
  CAR_CARE_SESSION_NOT_FOUND: 'CAR_CARE_SESSION_NOT_FOUND',

  /* maintenance */
  MAINTENANCE_RECORD_NOT_FOUND: 'MAINTENANCE_RECORD_NOT_FOUND',

  /* energy */
  ODOMETER_VALUE_TOO_LOW: 'ODOMETER_VALUE_TOO_LOW',
  ENERGY_SESSION_NOT_FOUND: 'ENERGY_SESSION_NOT_FOUND',

  /* vehicle */
  VEHICLE_PLATE_ALREADY_EXISTS: 'VEHICLE_PLATE_ALREADY_EXISTS',
  VEHICLE_NOT_FOUND: 'VEHICLE_NOT_FOUND',

  /* media */
  IMAGE_NOT_FOUND: 'IMAGE_NOT_FOUND',
  OWNER_IMAGES_NOT_FOUND: 'OWNER_IMAGES_NOT_FOUND',
  OWNER_IMAGE_OF_KIND_NOT_FOUND: 'OWNER_IMAGE_OF_KIND_NOT_FOUND',

  /* server */
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const
